#!/bin/bash

set -euo pipefail

OWN_FILENAME="$(basename $0)"
LAMBDA_EXTENSION_NAME="$OWN_FILENAME"

echo "${LAMBDA_EXTENSION_NAME}  launching extension"
python3 "/opt/${LAMBDA_EXTENSION_NAME}/extension.py"